export const HOME = '/'
export const BUSINESS_LOANS = '/business-loans'
export const PERSONAL_LOANS = '/personal-loans'
export const PERSONAL_ACCOUNTS = '/personal-accounts'
export const BUSINESS_ACCOUNTS = '/business-accounts'
export const PERSONAL_FINANCINGS = '/personal-financings'
export const BUSINESS_FINANCINGS = '/business-financings'
