export const HOME = '/'
export const BUSINESS_LOANS = '/business-loans'
export const PERSONAL_LOANS = '/personal-loans'
export const PERSONAL_ACCOUNTS = '/personal-accounts'
export const PERSONAL_CREDIT_CARDS = '/personal-credit-cards'
export const BUSINESS_ACCOUNT = '/business-accounts'
